language: c

compiler:
  - gcc

before_install:
 - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsdl2-dev
 - curl -O http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz
 - tar xf SDL2_gfx-1.0.1.tar.gz
 - cd SDL2_gfx-1.0.1 && ./autogen.sh && ./configure
 - make && sudo make install
 - cd ..

script: make
